"""Default vegetarian grocery recommendations (German) shown in the autocomplete dropdown.

Grouped for readability. The order within the tuple is the display priority
when multiple recommendations match the same query.
"""

VEGETARIAN_RECOMMENDATIONS = (
    # Obst
    "Äpfel",
    "Bananen",
    "Orangen",
    "Birnen",
    "Zitronen",
    "Trauben",
    "Erdbeeren",
    "Himbeeren",
    "Heidelbeeren",
    "Avocado",
    # Gemüse
    "Tomaten",
    "Gurken",
    "Paprika",
    "Karotten",
    "Kartoffeln",
    "Zwiebeln",
    "Knoblauch",
    "Kopfsalat",
    "Spinat",
    "Brokkoli",
    "Blumenkohl",
    "Zucchini",
    "Aubergine",
    "Pilze",
    "Champignons",
    "Mais",
    "Oliven",
    # Milchprodukte & pflanzliche Alternativen
    "Milch",
    "Hafermilch",
    "Mandelmilch",
    "Butter",
    "Margarine",
    "Frischkäse",
    "Käse",
    "Joghurt",
    "Quark",
    "Sahne",
    "Skyr",
    "Mozzarella",
    "Feta",
    # Brot & Backwaren
    "Brot",
    "Brötchen",
    "Vollkornbrot",
    "Toastbrot",
    "Knäckebrot",
    # Getreide & Hülsenfrüchte
    "Nudeln",
    "Spaghetti",
    "Reis",
    "Couscous",
    "Quinoa",
    "Haferflocken",
    "Müsli",
    "Linsen",
    "Kichererbsen",
    "Bohnen",
    # Eier & pflanzliche Proteine
    "Eier",
    "Tofu",
    "Tempeh",
    "Seitan",
    "Räuchertofu",
    # Aufstriche
    "Marmelade",
    "Honig",
    "Erdnussbutter",
    "Hummus",
    "Pesto",
    # Öle & Gewürze
    "Olivenöl",
    "Rapsöl",
    "Essig",
    "Salz",
    "Pfeffer",
    "Zucker",
    # Getränke
    "Mineralwasser",
    "Apfelsaft",
    "Orangensaft",
    "Kaffee",
    "Tee",
    # Snacks & Nüsse
    "Schokolade",
    "Kekse",
    "Mandeln",
    "Walnüsse",
    "Haselnüsse",
    # Konserven & Tiefkühl
    "Tomatenmark",
    "Dosentomaten",
    "Tiefkühlgemüse",
    "Tiefkühlbeeren",
)
